---
- name: "{{ epics_modules[item].name }} | Create mandatory configure/RELEASE.local"
  ansible.builtin.copy:
    dest: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/configure/RELEASE.local"
    content: |
      -include $(TOP)/../RELEASE.local
  become: true

- name: "{{ epics_modules[item].name }} | Run configuration step"
  ansible.builtin.command: |
    make -C "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}" configure "EPICS_BASE={{ epics_install_path }}/base-{{ epics_modules['base'].version }}"
  become: true
