---
- name: Install common packages
  apt: 
    name: ['g++']
    state: latest
    update_cache: yes
  become: true
  register: apt_result
  retries: 3
  delay: 5
  until: apt_result is succeeded

- name: Create installation directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: true
  loop:
    - "{{ epics_install_path }}"
    - "{{ epics_install_path }}/RELEASE.local.d"
    - "{{ epics_install_path }}/epics-tools.sh.d"
    - "{{ epics_install_path }}/.flag"
    - "{{ opi_install_path }}"

