---
# tasks file for sysupdate
- name: Update and Upgrade APT Packages
  tags: systupdate, never
  block:
    - name: Update APT packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Upgrade APT packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
      become: true

    - name: Check for the reboot-required file
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600  # Adjust as needed
        test_command: whoami  # Adjust as needed, this is just a placeholder command
      when: reboot_required.stat.exists | default(false)
      become: true

    - name: Wait for the system to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300  # Adjust as needed
      when: reboot_required.stat.exists | default(false)

    - name: Run apt autoremove
      ansible.builtin.apt:
        autoremove: true
      become: true
