epics_modules:

  base:
    name: "EPICS Base"
    version: "7.0.8"
    url: "https://epics-controls.org/download/base/base-7.0.8.tar.gz"
    release_var: "EPICS_BASE"
    release_sortkey: "99"
    add_to_path: true
    required_debs:
      - build-essential
      - libreadline-dev
      - libncurses-dev
      - libc6-dev
      - perl
      - libperl-dev
      - libtest-simple-perl
      - libtest-harness-perl
    pre_hook: base_prep.yml

  pvxs:
    name: "PVXS"
    version: "1.3.1"
    url: "https://github.com/mdavidsaver/pvxs/archive/refs/tags/1.3.1.tar.gz"
    release_var: "PVXS"
    release_sortkey: "10"
    add_to_path: true
    required_debs:
      - libevent-dev

  p4p:
    name: "p4p"
    version: "4.1.12"
    url: "https://github.com/mdavidsaver/p4p/archive/refs/tags/4.1.12.tar.gz"
    release_var: "P4P"
    release_sortkey: "10"
    required_debs:
      - python3-dev
      - python3-numpy
      - python3-nose2
      - cython3
    pre_hook: p4p_prep.yml

  seq:
    name: "SNL Sequencer"
    version: "2.2.9"
    url: "https://github.com/epics-modules/sequencer/archive/refs/tags/R2-2-9.tar.gz"
    release_var: "SNCSEQ"
    release_sortkey: "10"
    add_to_path: true
    required_debs:
      - re2c

  asyn:
    name: "ASYN"
    version: "4.44.2"
    url: "https://github.com/epics-modules/asyn/archive/refs/tags/R4-44-2.tar.gz"
    release_var: "ASYN"
    release_sortkey: "10"
    required_debs:
      - libtirpc-dev
    pre_hook: asyn_prep.yml

  autosave:
    name: "autoSaveRestore"
    version: "5.11"
    url: "https://github.com/epics-modules/autosave/archive/refs/tags/R5-11.tar.gz"
    release_var:  "AUTOSAVE"
    release_sortkey: "10"

  busy:
    name: "Busy Record"
    version: "1.7.4"
    url: "https://github.com/epics-modules/busy/archive/refs/tags/R1-7-4.tar.gz"
    release_var: "BUSY"
    release_sortkey: "10"

  sscan:
    name: "SScan module"
    version: "2.11.6"
    url: "https://github.com/epics-modules/sscan/archive/refs/tags/R2-11-6.tar.gz"
    release_var: "SSCAN"
    release_sortkey: "10"

  calc:
    name: "Calc module (misc records)"
    version: "3.7.5"
    url: "https://github.com/epics-modules/calc/archive/refs/tags/R3-7-5.tar.gz"
    release_var: "CALC"
    release_sortkey: "10"
  
  pcre:
    name: "PCRE"
    version: "R8-44"
    url: "https://github.com/chrschroeder/pcre/archive/refs/tags/R8-44.tar.gz"
    release_var: "PCRE"
    release_sortkey: "10"
    required_debs:
      - libpcre3-dev
  
  stream:
    name: "StreamDevice"
    version: "2.8.24"
    url: "https://github.com/paulscherrerinstitute/StreamDevice/archive/refs/tags/2.8.24.tar.gz"
    release_var: "STREAM"
    release_sortkey: "10"

  adcore:
    name: "AreaDetector - Core"
    version: "3.13"
    url: "https://github.com/areaDetector/ADCore/archive/refs/tags/R3-13.tar.gz"
    release_var: "ADCORE"
    release_sortkey: "10"
    required_debs:
      - zlib1g-dev
      - libtiff5
      - libjpeg-turbo8
      - libzstd1
      - libaravis-0.8-0 
      - libaravis-dev
      - libx11-dev
      - libxcomposite-dev
      - libboost1.74-dev
      - libboost-test-dev
      - libboost-system-dev
      - libxml2-dev
      - libtiff-dev
      - libjpeg-dev
      - libpng-dev 
      - libpng++-dev 
      - libhdf5-dev
    pre_hook: adcore_prep.yml

  adsimdetector:
    name: "AreaDetector - SimDetector"
    version: "2.11"
    url: "https://github.com/areaDetector/ADSimDetector/archive/refs/tags/R2-11.tar.gz"
    release_var: "ADSIMDETECTOR"
    release_sortkey: "10"
    pre_hook: adsimdetector_prep.yml

  adpvadriver:
    name: "AreaDetector - pvaDriver"
    version: "1.6"
    url: "https://github.com/areaDetector/pvaDriver/archive/refs/tags/R1-6.tar.gz"
    release_var: "PVADRIVER"
    release_sortkey: "10"
    pre_hook: adpvadriver_prep.yml
    
  motor:
    name: "Motor Record"
    version: "R7-3-1"
    url: "https://github.com/epics-modules/motor/archive/refs/tags/R7-3-1.tar.gz"
    release_var: "MOTOR"
    release_sortkey: "10"