- name: Install docker.io
  ansible.builtin.apt:
    name: docker.io
    state: present
  notify: Docker deamon configuration changed
  become: yes

- name: Install other docker modules
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-compose
  become: yes

- name: Configuring docker proxy
  tags: docker-proxy
  ansible.builtin.import_tasks: docker.proxy.yaml
  when: webproxy_url is defined

- name: Configuring docker client proxy
  tags: docker-users
  ansible.builtin.import_tasks: docker.users.yaml
  when: docker_users is defined
