---
- name: Set up training VM
  hosts: local
  gather_facts: true
  gather_subset: ["system", "!all", "!min"]
  vars:
    docker_users: epics  
  roles:
    - role: sysupdate
      
    - role: common        #  <- mandatory
      tags: common

    - role: epics-modules
      tags: epics_modules
      when: epics_modules

    - role: phoebus

    - role: docker
      tags: docker
      when: docker

    - role: bluesky
      tags: bluesky
      when: bluesky

    - role: epics-tools


